default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  username: root
  password: root

development:
  <<: *default
  database: tasks_development

test:
  <<: *default
  database: tasks_test

production:
  <<: *default
  database: tasks_production
  username: tasks
  password: <%= ENV['TASKS_DATABASE_PASSWORD'] %>
